import { Quiz, QuizAttempt, QuizResult } from '@studysphere/shared-types';

export const mockQuizzes: Quiz[] = [
  {
    id: 'quiz-001',
    subjectId: 'sub-dbms-301',
    createdBy: 'usr-stu-001',
    title: 'Relational Normalization & BCNF Decomposition Assessment',
    source: 'ai',
    questionCount: 10,
    difficulty: 'medium',
    timeLimitMinutes: 15,
    tokensUsed: 140,
    topicsCovered: [
      'First, Second & Third Normal Forms',
      'Boyce-Codd Normal Form (BCNF)',
      'Lossless Join Decomposition',
      'Dependency Preservation',
      'Multivalued Dependencies & 4NF',
    ],
    createdAt: '2026-08-28T10:00:00Z',
    updatedAt: '2026-08-28T10:00:00Z',
    questions: [
      {
        id: 'q-dbms-01',
        quizId: 'quiz-001',
        type: 'mcq',
        prompt: 'Which normal form strictly guarantees that for every non-trivial functional dependency X -> Y, X must be a superkey of the relation schema?',
        options: [
          { id: 'opt-a', text: 'First Normal Form (1NF)' },
          { id: 'opt-b', text: 'Second Normal Form (2NF)' },
          { id: 'opt-c', text: 'Third Normal Form (3NF)' },
          { id: 'opt-d', text: 'Boyce-Codd Normal Form (BCNF)' },
        ],
        correctAnswer: 'Boyce-Codd Normal Form (BCNF)',
        explanation: 'BCNF requires every determinant (left-hand side of a non-trivial FD) to be a superkey. Unlike 3NF, BCNF does not allow prime attribute exceptions on the right-hand side.',
        topicTag: 'BCNF Definition',
        marks: 2,
        difficulty: 'medium',
        citation: 'Silberschatz Database System Concepts, Chapter 8, Section 8.3',
        createdAt: '2026-08-28T10:00:00Z',
        updatedAt: '2026-08-28T10:00:00Z',
      },
      {
        id: 'q-dbms-02',
        quizId: 'quiz-001',
        type: 'mcq',
        prompt: 'A relation schema R is decomposed into R1 and R2. Which condition mathematically proves that the decomposition is lossless with respect to a set of functional dependencies F?',
        options: [
          { id: 'opt-a', text: '(R1 ∩ R2) -> R1 ∈ F+ OR (R1 ∩ R2) -> R2 ∈ F+' },
          { id: 'opt-b', text: '(R1 ∪ R2) -> R1 ∈ F+' },
          { id: 'opt-c', text: 'R1 ∩ R2 = ∅ (Empty intersection)' },
          { id: 'opt-d', text: 'R1 and R2 have equal number of attributes' },
        ],
        correctAnswer: '(R1 ∩ R2) -> R1 ∈ F+ OR (R1 ∩ R2) -> R2 ∈ F+',
        explanation: 'By the Lossless Join Theorem, a binary decomposition is lossless if and only if the common attributes form a superkey of at least one of the decomposed schemas.',
        topicTag: 'Lossless Decomposition',
        marks: 2,
        difficulty: 'hard',
        citation: 'Elmasri & Navathe Fundamentals of Database Systems, Chapter 14',
        createdAt: '2026-08-28T10:00:00Z',
        updatedAt: '2026-08-28T10:00:00Z',
      },
      {
        id: 'q-dbms-03',
        quizId: 'quiz-001',
        type: 'true_false',
        prompt: 'True or False: Every relation schema can be decomposed into BCNF while simultaneously guaranteeing dependency preservation.',
        options: [
          { id: 'opt-t', text: 'True' },
          { id: 'opt-f', text: 'False' },
        ],
        correctAnswer: 'False',
        explanation: 'False. 3NF decomposition guarantees both lossless join and dependency preservation, but BCNF decomposition cannot always preserve all functional dependencies.',
        topicTag: 'Dependency Preservation',
        marks: 1,
        difficulty: 'medium',
        citation: 'Database Systems Ledger, Section 4.2',
        createdAt: '2026-08-28T10:00:00Z',
        updatedAt: '2026-08-28T10:00:00Z',
      },
      {
        id: 'q-dbms-04',
        quizId: 'quiz-001',
        type: 'fill_blank',
        prompt: 'A functional dependency X -> Y is called ________ if Y is a subset of X.',
        options: null,
        correctAnswer: 'trivial',
        explanation: 'A functional dependency is trivial by definition if the right-hand attribute set is completely contained within the left-hand attribute set (e.g. {A, B} -> A).',
        topicTag: 'Functional Dependencies',
        marks: 1,
        difficulty: 'easy',
        citation: 'DBMS Syllabus Unit 3',
        createdAt: '2026-08-28T10:00:00Z',
        updatedAt: '2026-08-28T10:00:00Z',
      },
      {
        id: 'q-dbms-05',
        quizId: 'quiz-001',
        type: 'short_answer',
        prompt: 'State the primary anomaly that Fourth Normal Form (4NF) is designed to eliminate.',
        options: null,
        correctAnswer: 'Multivalued dependency anomalies / redundancy from independent multi-valued attributes',
        explanation: '4NF eliminates redundancies and update anomalies caused by non-trivial Multivalued Dependencies (MVDs) where independent 1-to-many relationships are modeled in a single table.',
        topicTag: 'Multivalued Dependencies & 4NF',
        marks: 2,
        difficulty: 'hard',
        citation: 'Database Research Ledger, Chapter 7',
        createdAt: '2026-08-28T10:00:00Z',
        updatedAt: '2026-08-28T10:00:00Z',
      },
    ],
  },
  {
    id: 'quiz-002',
    subjectId: 'sub-os-302',
    createdBy: 'usr-stu-001',
    title: 'Operating Systems: Virtual Memory & Page Replacement Algorithms',
    source: 'ai',
    questionCount: 8,
    difficulty: 'medium',
    timeLimitMinutes: 12,
    tokensUsed: 110,
    topicsCovered: [
      'Paging & Address Translation',
      'Page Fault Handling',
      'Belady’s Anomaly & FIFO',
      'Least Recently Used (LRU) & Clock Algorithm',
    ],
    createdAt: '2026-08-29T14:30:00Z',
    updatedAt: '2026-08-29T14:30:00Z',
    questions: [
      {
        id: 'q-os-01',
        quizId: 'quiz-002',
        type: 'mcq',
        prompt: 'Which page replacement algorithm is theoretically optimal but impossible to implement in practice because it requires future knowledge of reference strings?',
        options: [
          { id: 'opt-a', text: 'First-In, First-Out (FIFO)' },
          { id: 'opt-b', text: 'Least Recently Used (LRU)' },
          { id: 'opt-c', text: 'Belady’s Optimal Algorithm (OPT)' },
          { id: 'opt-d', text: 'Clock Page Replacement' },
        ],
        correctAnswer: 'Belady’s Optimal Algorithm (OPT)',
        explanation: 'OPT replaces the page that will not be used for the longest period of time in the future. Since operating systems cannot predict future memory references, OPT serves solely as a benchmark.',
        topicTag: 'Page Replacement Algorithms',
        marks: 2,
        difficulty: 'easy',
        citation: 'Silberschatz Operating System Concepts, Chapter 10',
        createdAt: '2026-08-29T14:30:00Z',
        updatedAt: '2026-08-29T14:30:00Z',
      },
    ],
  },
];

export const mockQuizResults: Record<string, QuizResult> = {
  'attempt-001': {
    attemptId: 'attempt-001',
    quizId: 'quiz-001',
    quizTitle: 'Relational Normalization & BCNF Decomposition Assessment',
    score: 92,
    totalMarks: 20,
    totalQuestions: 10,
    correctCount: 9,
    incorrectCount: 1,
    skippedCount: 0,
    accuracy: 90,
    timeTakenSeconds: 684,
    percentile: 96,
    rank: 3,
    weakTopics: [
      {
        topic: 'BCNF Definition & Superkey Rules',
        totalQuestions: 3,
        correctCount: 3,
        accuracyPercentage: 100,
        masteryStatus: 'mastered',
      },
      {
        topic: 'Lossless Join Decomposition',
        totalQuestions: 4,
        correctCount: 4,
        accuracyPercentage: 100,
        masteryStatus: 'mastered',
      },
      {
        topic: 'Multivalued Dependencies (4NF)',
        totalQuestions: 3,
        correctCount: 2,
        accuracyPercentage: 66,
        masteryStatus: 'needs_revision',
      },
    ],
    answers: [
      {
        questionId: 'q-dbms-01',
        prompt: 'Which normal form strictly guarantees that for every non-trivial functional dependency X -> Y, X must be a superkey of the relation schema?',
        type: 'mcq',
        selectedAnswer: 'Boyce-Codd Normal Form (BCNF)',
        correctAnswer: 'Boyce-Codd Normal Form (BCNF)',
        isCorrect: true,
        explanation: 'BCNF requires every determinant to be a superkey, eliminating transitive and partial dependencies without prime attribute exceptions.',
        topicTag: 'BCNF Definition',
        citation: 'Silberschatz Database System Concepts, Chapter 8',
      },
      {
        questionId: 'q-dbms-02',
        prompt: 'A relation schema R is decomposed into R1 and R2. Which condition mathematically proves that the decomposition is lossless with respect to a set of functional dependencies F?',
        type: 'mcq',
        selectedAnswer: '(R1 ∩ R2) -> R1 ∈ F+ OR (R1 ∩ R2) -> R2 ∈ F+',
        correctAnswer: '(R1 ∩ R2) -> R1 ∈ F+ OR (R1 ∩ R2) -> R2 ∈ F+',
        isCorrect: true,
        explanation: 'By the Lossless Join Theorem, the intersection of attributes must contain a candidate key for at least one of the sub-relations.',
        topicTag: 'Lossless Decomposition',
        citation: 'Elmasri & Navathe Chapter 14',
      },
      {
        questionId: 'q-dbms-03',
        prompt: 'True or False: Every relation schema can be decomposed into BCNF while simultaneously guaranteeing dependency preservation.',
        type: 'true_false',
        selectedAnswer: 'False',
        correctAnswer: 'False',
        isCorrect: true,
        explanation: '3NF guarantees dependency preservation, but BCNF decomposition cannot always preserve all functional dependencies.',
        topicTag: 'Dependency Preservation',
        citation: 'Database Systems Ledger, Section 4.2',
      },
    ],
  },
};

export const mockQuizAttempts: QuizAttempt[] = [
  {
    id: 'attempt-001',
    quizId: 'quiz-001',
    userId: 'usr-stu-001',
    score: 92,
    accuracy: 90,
    startedAt: '2026-08-28T10:05:00Z',
    submittedAt: '2026-08-28T10:16:24Z',
    timeTakenSeconds: 684,
    createdAt: '2026-08-28T10:05:00Z',
    updatedAt: '2026-08-28T10:16:24Z',
  },
  {
    id: 'attempt-002',
    quizId: 'quiz-002',
    userId: 'usr-stu-001',
    score: 85,
    accuracy: 87.5,
    startedAt: '2026-08-29T15:00:00Z',
    submittedAt: '2026-08-29T15:10:45Z',
    timeTakenSeconds: 645,
    createdAt: '2026-08-29T15:00:00Z',
    updatedAt: '2026-08-29T15:10:45Z',
  },
];
