import {
  StudyPlan,
  StudySessionItem,
  WeeklyScheduleDay,
  RevisionMilestone,
  MockTestSuggestion,
  SubjectReadiness,
} from '@studysphere/shared-types';

export const mockTodayStudySessions: StudySessionItem[] = [
  {
    id: 'ses-001',
    subjectId: 'sub-dbms',
    subjectCode: 'CS-301',
    subjectName: 'Database Management Systems',
    topic: 'Relational Normalization & BCNF Decomposition Proofs',
    startTime: '09:00',
    endTime: '10:30',
    durationMinutes: 90,
    type: 'study',
    status: 'completed',
    completedAt: '2026-08-30T10:28:00Z',
  },
  {
    id: 'ses-002',
    subjectId: 'sub-os',
    subjectCode: 'CS-303',
    subjectName: 'Operating Systems',
    topic: 'Virtual Memory Paging, Inverted Tables & TLB Hit Ratio',
    startTime: '10:45',
    endTime: '12:15',
    durationMinutes: 90,
    type: 'study',
    status: 'upcoming',
  },
  {
    id: 'ses-003',
    subjectId: 'sub-algo',
    subjectCode: 'CS-302',
    subjectName: 'Design & Analysis of Algorithms',
    topic: 'Dynamic Programming: Matrix Chain Multiplication & TSP',
    startTime: '14:00',
    endTime: '15:30',
    durationMinutes: 90,
    type: 'problem_set',
    status: 'upcoming',
  },
  {
    id: 'ses-004',
    subjectId: 'sub-dbms',
    subjectCode: 'CS-301',
    subjectName: 'Database Management Systems',
    topic: 'Diagnostic Quiz Practice: Functional Dependencies',
    startTime: '16:00',
    endTime: '17:00',
    durationMinutes: 60,
    type: 'mock_quiz',
    status: 'upcoming',
  },
];

export const mockWeeklySchedule: WeeklyScheduleDay[] = [
  {
    day: 'Monday',
    date: 'Aug 31',
    totalHours: 5.5,
    priority: 'high',
    sessions: [
      {
        id: 'w-mon-1',
        subjectId: 'sub-dbms',
        subjectCode: 'CS-301',
        subjectName: 'DBMS',
        topic: 'BCNF Proofs & Multi-Valued Dependencies',
        startTime: '09:00',
        endTime: '11:00',
        durationMinutes: 120,
        type: 'study',
        status: 'upcoming',
      },
      {
        id: 'w-mon-2',
        subjectId: 'sub-os',
        subjectCode: 'CS-303',
        subjectName: 'Operating Systems',
        topic: 'Page Replacement Algorithms (LRU, Optimal)',
        startTime: '14:00',
        endTime: '16:00',
        durationMinutes: 120,
        type: 'study',
        status: 'upcoming',
      },
      {
        id: 'w-mon-3',
        subjectId: 'sub-algo',
        subjectCode: 'CS-302',
        subjectName: 'Algorithms',
        topic: 'Greedy vs DP Strategy Problems',
        startTime: '17:00',
        endTime: '18:30',
        durationMinutes: 90,
        type: 'problem_set',
        status: 'upcoming',
      },
    ],
  },
  {
    day: 'Tuesday',
    date: 'Sep 01',
    totalHours: 6.0,
    priority: 'high',
    sessions: [
      {
        id: 'w-tue-1',
        subjectId: 'sub-algo',
        subjectCode: 'CS-302',
        subjectName: 'Algorithms',
        topic: 'Graph Algorithms: Tarjan SCC & Dijkstra',
        startTime: '09:00',
        endTime: '12:00',
        durationMinutes: 180,
        type: 'study',
        status: 'upcoming',
      },
      {
        id: 'w-tue-2',
        subjectId: 'sub-cn',
        subjectCode: 'CS-304',
        subjectName: 'Computer Networks',
        topic: 'TCP Congestion Control & Sliding Window',
        startTime: '15:00',
        endTime: '18:00',
        durationMinutes: 180,
        type: 'study',
        status: 'upcoming',
      },
    ],
  },
  {
    day: 'Wednesday',
    date: 'Sep 02',
    totalHours: 4.5,
    priority: 'medium',
    sessions: [
      {
        id: 'w-wed-1',
        subjectId: 'sub-dbms',
        subjectCode: 'CS-301',
        subjectName: 'DBMS',
        topic: 'Transaction ACID Properties & Two-Phase Locking',
        startTime: '09:00',
        endTime: '11:30',
        durationMinutes: 150,
        type: 'study',
        status: 'upcoming',
      },
      {
        id: 'w-wed-2',
        subjectId: 'sub-os',
        subjectCode: 'CS-303',
        subjectName: 'Operating Systems',
        topic: 'Deadlock Detection & Banker Algorithm',
        startTime: '14:00',
        endTime: '16:00',
        durationMinutes: 120,
        type: 'study',
        status: 'upcoming',
      },
    ],
  },
  {
    day: 'Thursday',
    date: 'Sep 03',
    totalHours: 6.0,
    priority: 'high',
    sessions: [
      {
        id: 'w-thu-1',
        subjectId: 'sub-os',
        subjectCode: 'CS-303',
        subjectName: 'Operating Systems',
        topic: 'Semaphores, Monitors & Producer-Consumer',
        startTime: '09:00',
        endTime: '12:00',
        durationMinutes: 180,
        type: 'study',
        status: 'upcoming',
      },
      {
        id: 'w-thu-2',
        subjectId: 'sub-algo',
        subjectCode: 'CS-302',
        subjectName: 'Algorithms',
        topic: 'NP-Completeness: 3-SAT & Vertex Cover',
        startTime: '15:00',
        endTime: '18:00',
        durationMinutes: 180,
        type: 'study',
        status: 'upcoming',
      },
    ],
  },
  {
    day: 'Friday',
    date: 'Sep 04',
    totalHours: 5.0,
    priority: 'medium',
    sessions: [
      {
        id: 'w-fri-1',
        subjectId: 'sub-cn',
        subjectCode: 'CS-304',
        subjectName: 'Computer Networks',
        topic: 'Subnetting, CIDR & BGP Routing Protocols',
        startTime: '09:00',
        endTime: '12:00',
        durationMinutes: 180,
        type: 'study',
        status: 'upcoming',
      },
      {
        id: 'w-fri-2',
        subjectId: 'sub-dbms',
        subjectCode: 'CS-301',
        subjectName: 'DBMS',
        topic: 'Crash Recovery: WAL Protocol & ARIES Algorithm',
        startTime: '14:30',
        endTime: '16:30',
        durationMinutes: 120,
        type: 'revision',
        status: 'upcoming',
      },
    ],
  },
  {
    day: 'Saturday',
    date: 'Sep 05',
    totalHours: 7.0,
    priority: 'high',
    sessions: [
      {
        id: 'w-sat-1',
        subjectId: 'sub-dbms',
        subjectCode: 'CS-301',
        subjectName: 'DBMS',
        topic: 'Full Midterm Simulator Mock Exam',
        startTime: '10:00',
        endTime: '13:00',
        durationMinutes: 180,
        type: 'mock_quiz',
        status: 'upcoming',
      },
      {
        id: 'w-sat-2',
        subjectId: 'sub-os',
        subjectCode: 'CS-303',
        subjectName: 'Operating Systems',
        topic: 'High-Yield PYQ Problem Set Solving',
        startTime: '15:00',
        endTime: '19:00',
        durationMinutes: 240,
        type: 'problem_set',
        status: 'upcoming',
      },
    ],
  },
  {
    day: 'Sunday',
    date: 'Sep 06',
    totalHours: 4.0,
    priority: 'normal',
    sessions: [
      {
        id: 'w-sun-1',
        subjectId: 'sub-algo',
        subjectCode: 'CS-302',
        subjectName: 'Algorithms',
        topic: 'Weekly Revision & Flashcard Recall',
        startTime: '10:00',
        endTime: '12:00',
        durationMinutes: 120,
        type: 'revision',
        status: 'upcoming',
      },
      {
        id: 'w-sun-2',
        subjectId: 'sub-cn',
        subjectCode: 'CS-304',
        subjectName: 'Computer Networks',
        topic: 'Weekly Concept Map Review',
        startTime: '15:00',
        endTime: '17:00',
        durationMinutes: 120,
        type: 'revision',
        status: 'upcoming',
      },
    ],
  },
];

export const mockRevisionMilestones: RevisionMilestone[] = [
  {
    subject: 'Database Management Systems',
    subjectCode: 'CS-301',
    examDate: '2026-10-14',
    tMinus7Date: '2026-10-07 (Deep Slide Synthesis)',
    tMinus3Date: '2026-10-11 (High-Yield PYQs & Proofs)',
    tMinus1Date: '2026-10-13 (Formula & Theorem Recall)',
    coveragePercentage: 88,
    intensity: 'deep',
  },
  {
    subject: 'Operating Systems',
    subjectCode: 'CS-303',
    examDate: '2026-10-20',
    tMinus7Date: '2026-10-13 (Kernel & Memory Derivations)',
    tMinus3Date: '2026-10-17 (Page Replacement Simulations)',
    tMinus1Date: '2026-10-19 (Architecture Summary Cards)',
    coveragePercentage: 76,
    intensity: 'high_yield',
  },
  {
    subject: 'Design & Analysis of Algorithms',
    subjectCode: 'CS-302',
    examDate: '2026-10-28',
    tMinus7Date: '2026-10-21 (Master Theorem & DP Recurrences)',
    tMinus3Date: '2026-10-25 (NP Proof Reductions)',
    tMinus1Date: '2026-10-27 (Big-O Complexity Matrix)',
    coveragePercentage: 68,
    intensity: 'deep',
  },
  {
    subject: 'Computer Networks',
    subjectCode: 'CS-304',
    examDate: '2026-11-04',
    tMinus7Date: '2026-10-28 (OSI/TCP Layer Protocols)',
    tMinus3Date: '2026-11-01 (Routing Calculation Practice)',
    tMinus1Date: '2026-11-03 (Header Bitfields Cheat Sheet)',
    coveragePercentage: 54,
    intensity: 'high_yield',
  },
];

export const mockMockTestSuggestions: MockTestSuggestion[] = [
  {
    id: 'mock-001',
    subject: 'Database Management Systems',
    subjectCode: 'CS-301',
    topic: 'Relational Normalization & BCNF Decomposition Proofs',
    suggestedDate: 'Saturday, Sep 05 at 10:00 AM',
    difficulty: 'hard',
    durationMinutes: 45,
    targetScore: 90,
    reason: 'Targeted remediation: Quiz accuracy in functional dependencies is 74% (Target: 90%).',
  },
  {
    id: 'mock-002',
    subject: 'Operating Systems',
    subjectCode: 'CS-303',
    topic: 'Virtual Memory, Inverted Page Tables & Paging',
    suggestedDate: 'Sunday, Sep 06 at 03:00 PM',
    difficulty: 'medium',
    durationMinutes: 40,
    targetScore: 88,
    reason: 'Exam milestone: 20 days remaining until Midterm Exam Hall session.',
  },
];

export const mockSubjectReadiness: SubjectReadiness[] = [
  {
    id: 'sub-dbms',
    subject: 'Database Management Systems',
    code: 'CS-301',
    coveragePercentage: 88,
    examDate: '2026-10-14',
    daysLeft: 12,
    quizAccuracy: 94,
    status: 'on_track',
  },
  {
    id: 'sub-os',
    subject: 'Operating Systems',
    code: 'CS-303',
    coveragePercentage: 76,
    examDate: '2026-10-20',
    daysLeft: 18,
    quizAccuracy: 91,
    status: 'on_track',
  },
  {
    id: 'sub-algo',
    subject: 'Design & Analysis of Algorithms',
    code: 'CS-302',
    coveragePercentage: 68,
    examDate: '2026-10-28',
    daysLeft: 26,
    quizAccuracy: 88,
    status: 'needs_attention',
  },
  {
    id: 'sub-cn',
    subject: 'Computer Networks',
    code: 'CS-304',
    coveragePercentage: 54,
    examDate: '2026-11-04',
    daysLeft: 33,
    quizAccuracy: 82,
    status: 'needs_attention',
  },
];

export const mockStudyPlan: StudyPlan = {
  id: 'plan-001',
  title: 'Semester 5 Exam Readiness Master Plan',
  dailyHours: 6.0,
  preferredPattern: 'morning',
  readinessScore: 84,
  streakDays: 12,
  todaySessions: mockTodayStudySessions,
  weeklySchedule: mockWeeklySchedule,
  revisionMilestones: mockRevisionMilestones,
  mockTestSuggestions: mockMockTestSuggestions,
  subjectReadiness: mockSubjectReadiness,
  createdAt: '2026-08-30T09:00:00Z',
  updatedAt: '2026-08-30T10:30:00Z',
};
