import { Resource, Comment, ContributorPoints, LeaderboardEntry } from '@studysphere/shared-types';
import { mockStudentUser, mockFacultyUser, mockAlumniUser } from './users.mock.js';

export const mockResourcesList: Resource[] = [
  {
    id: 'res-101',
    title: 'Complete DBMS Normalization (1NF to 5NF) Handwritten Notes',
    description: 'Comprehensive lecture and revision notes covering 1NF, 2NF, 3NF, BCNF, 4NF, 5NF with real university exam proofs and decomposition trees.',
    type: 'notes',
    subjectId: 'CS-301 Database Systems',
    semester: 5,
    uploadedBy: 'usr-student-01',
    uploader: mockStudentUser,
    fileUrl: 'https://drive.google.com/file/d/1A2b3C4d5E6f7G8h9I0j-DBMS-Norm/view?usp=sharing',
    driveLink: 'https://drive.google.com/file/d/1A2b3C4d5E6f7G8h9I0j-DBMS-Norm/view?usp=sharing',
    fileMetadata: {
      driveFileId: '1A2b3C4d5E6f7G8h9I0j-DBMS-Norm',
      fileName: 'DBMS_Normalization_Master_Notes_2026.pdf',
      fileSizeFormatted: '4.8 MB',
      mimeType: 'application/pdf',
    },
    tags: ['Normalization', 'BCNF', 'RelationalSchema', 'MidtermPrep'],
    likesCount: 142,
    bookmarksCount: 68,
    downloadsCount: 234,
    commentsCount: 12,
    status: 'published',
    verifiedBy: 'Prof. K. Sharma (Faculty Lead)',
    createdAt: '2026-08-25T10:00:00.000Z',
    updatedAt: '2026-08-25T10:00:00.000Z',
  },
  {
    id: 'res-102',
    title: 'Operating Systems Previous 5 Years Solved End-Sem Question Papers',
    description: 'University end-sem question papers with complete step-by-step solutions on process scheduling algorithms, semaphore sync, and virtual memory paging.',
    type: 'pyq',
    subjectId: 'CS-303 Operating Systems',
    semester: 5,
    uploadedBy: 'usr-faculty-01',
    uploader: mockFacultyUser,
    fileUrl: 'https://drive.google.com/file/d/2B3c4D5e6F7g8H9i0J1k-OS-PYQs/view?usp=sharing',
    driveLink: 'https://drive.google.com/file/d/2B3c4D5e6F7g8H9i0J1k-OS-PYQs/view?usp=sharing',
    fileMetadata: {
      driveFileId: '2B3c4D5e6F7g8H9i0J1k-OS-PYQs',
      fileName: 'OS_Solved_EndSem_2021_2025.pdf',
      fileSizeFormatted: '8.4 MB',
      mimeType: 'application/pdf',
    },
    tags: ['OperatingSystems', 'PYQ', 'Semaphores', 'Deadlocks', 'SolvedPapers'],
    likesCount: 230,
    bookmarksCount: 115,
    downloadsCount: 489,
    commentsCount: 19,
    status: 'published',
    verifiedBy: 'Department Academic Committee',
    createdAt: '2026-08-20T08:30:00.000Z',
    updatedAt: '2026-08-20T08:30:00.000Z',
  },
  {
    id: 'res-103',
    title: 'Design & Analysis of Algorithms: Dynamic Programming & Graph Code Packet',
    description: 'Detailed pseudocode, time complexity proofs, Dijkstra, Bellman-Ford, Floyd-Warshall, and 0/1 Knapsack visual state diagrams.',
    type: 'notes',
    subjectId: 'CS-302 Algorithms',
    semester: 5,
    uploadedBy: 'usr-student-01',
    uploader: mockStudentUser,
    fileUrl: 'https://drive.google.com/file/d/3C4d5E6f7G8h9I0j1K2l-Algorithms-DP/view?usp=sharing',
    driveLink: 'https://drive.google.com/file/d/3C4d5E6f7G8h9I0j1K2l-Algorithms-DP/view?usp=sharing',
    fileMetadata: {
      driveFileId: '3C4d5E6f7G8h9I0j1K2l-Algorithms-DP',
      fileName: 'DAA_DP_Graph_Algorithms_Verified.pdf',
      fileSizeFormatted: '6.1 MB',
      mimeType: 'application/pdf',
    },
    tags: ['Algorithms', 'DynamicProgramming', 'GraphTheory', 'ComplexityAnalysis'],
    likesCount: 188,
    bookmarksCount: 92,
    downloadsCount: 312,
    commentsCount: 8,
    status: 'published',
    verifiedBy: 'Prof. Ananya Sen',
    createdAt: '2026-08-18T14:15:00.000Z',
    updatedAt: '2026-08-18T14:15:00.000Z',
  },
  {
    id: 'res-104',
    title: 'Computer Networks Top-Down Protocol Layer Reference Guide',
    description: 'Protocol architecture diagrams, subnetting calculation cheat sheets, TCP 3-way handshake packet traces, and Wireshark lab manuals.',
    type: 'book',
    subjectId: 'CS-304 Computer Networks',
    semester: 5,
    uploadedBy: 'usr-alumni-01',
    uploader: mockAlumniUser,
    fileUrl: 'https://drive.google.com/file/d/4D5e6F7g8H9i0J1k2L3m-CN-Reference/view?usp=sharing',
    driveLink: 'https://drive.google.com/file/d/4D5e6F7g8H9i0J1k2L3m-CN-Reference/view?usp=sharing',
    fileMetadata: {
      driveFileId: '4D5e6F7g8H9i0J1k2L3m-CN-Reference',
      fileName: 'Computer_Networks_Reference_TopDown.pdf',
      fileSizeFormatted: '12.6 MB',
      mimeType: 'application/pdf',
    },
    tags: ['ComputerNetworks', 'TCP_IP', 'Subnetting', 'Wireshark', 'Protocols'],
    likesCount: 89,
    bookmarksCount: 44,
    downloadsCount: 178,
    commentsCount: 6,
    status: 'published',
    verifiedBy: 'Prof. R. Deshmukh',
    createdAt: '2026-08-15T12:00:00.000Z',
    updatedAt: '2026-08-15T12:00:00.000Z',
  },
  {
    id: 'res-105',
    title: 'Software Engineering Agile Sprint 2 & System Architecture Design Manual',
    description: 'Complete UML class diagrams, microservice interaction contracts, sequence diagrams, and CI/CD workflow documentation for semester project.',
    type: 'lab_manual',
    subjectId: 'CS-305 Software Engineering',
    semester: 5,
    uploadedBy: 'usr-student-01',
    uploader: mockStudentUser,
    fileUrl: 'https://drive.google.com/file/d/5E6f7G8h9I0j1K2l3M4n-SE-Lab/view?usp=sharing',
    driveLink: 'https://drive.google.com/file/d/5E6f7G8h9I0j1K2l3M4n-SE-Lab/view?usp=sharing',
    fileMetadata: {
      driveFileId: '5E6f7G8h9I0j1K2l3M4n-SE-Lab',
      fileName: 'SE_Lab_Manual_Sprint2_Architecture.pdf',
      fileSizeFormatted: '3.2 MB',
      mimeType: 'application/pdf',
    },
    tags: ['SoftwareEngineering', 'UML', 'Agile', 'LabManual', 'Architecture'],
    likesCount: 76,
    bookmarksCount: 38,
    downloadsCount: 142,
    commentsCount: 4,
    status: 'published',
    verifiedBy: 'Department Academic Committee',
    createdAt: '2026-08-12T09:30:00.000Z',
    updatedAt: '2026-08-12T09:30:00.000Z',
  },
  {
    id: 'res-106',
    title: 'B+ Tree Implementation in C++ & Storage Engine Optimization',
    description: 'Detailed research paper breakdown on B+ Tree buffer pool management and disk page latching strategies.',
    type: 'research_paper',
    subjectId: 'CS-301 Database Systems',
    semester: 5,
    uploadedBy: 'usr-student-01',
    uploader: mockStudentUser,
    fileUrl: 'https://drive.google.com/file/d/6F7g8H9i0J1k2L3m4N5o-BTree/view?usp=sharing',
    driveLink: 'https://drive.google.com/file/d/6F7g8H9i0J1k2L3m4N5o-BTree/view?usp=sharing',
    fileMetadata: {
      driveFileId: '6F7g8H9i0J1k2L3m4N5o-BTree',
      fileName: 'BPlusTree_Storage_Engine_Paper.pdf',
      fileSizeFormatted: '2.9 MB',
      mimeType: 'application/pdf',
    },
    tags: ['BTree', 'StorageEngine', 'CPP', 'ResearchPaper'],
    likesCount: 54,
    bookmarksCount: 29,
    downloadsCount: 96,
    commentsCount: 3,
    status: 'pending',
    createdAt: '2026-08-29T18:00:00.000Z',
    updatedAt: '2026-08-29T18:00:00.000Z',
  },
  {
    id: 'res-107',
    title: 'Computer Networks Transport Layer Sliding Window Simulator Notes',
    description: 'Go-Back-N and Selective Repeat protocol analysis with packet loss simulation worksheets.',
    type: 'notes',
    subjectId: 'CS-304 Computer Networks',
    semester: 5,
    uploadedBy: 'usr-student-01',
    uploader: mockStudentUser,
    fileUrl: 'https://drive.google.com/file/d/7G8h9I0j1K2l3M4n5O6p-SlidingWindow/view?usp=sharing',
    driveLink: 'https://drive.google.com/file/d/7G8h9I0j1K2l3M4n5O6p-SlidingWindow/view?usp=sharing',
    fileMetadata: {
      driveFileId: '7G8h9I0j1K2l3M4n5O6p-SlidingWindow',
      fileName: 'Sliding_Window_Protocols_Notes.pdf',
      fileSizeFormatted: '3.8 MB',
      mimeType: 'application/pdf',
    },
    tags: ['TransportLayer', 'GoBackN', 'SelectiveRepeat'],
    likesCount: 12,
    bookmarksCount: 5,
    downloadsCount: 22,
    commentsCount: 1,
    status: 'changes_requested',
    moderationFeedback: 'The Google Drive link permissions are set to restricted view. Please update Drive share setting to "Anyone with the link can view" and resubmit.',
    createdAt: '2026-08-28T11:20:00.000Z',
    updatedAt: '2026-08-29T09:00:00.000Z',
  },
  {
    id: 'res-108',
    title: 'Unverified Web Dev Slides Draft',
    description: 'Incomplete HTML5 / CSS3 revision slides deck without subject reference.',
    type: 'presentation',
    subjectId: 'CS-306 Web Technologies',
    semester: 5,
    uploadedBy: 'usr-student-01',
    uploader: mockStudentUser,
    fileUrl: 'https://drive.google.com/file/d/8H9i0J1k2L3m4N5o6P7q-Draft/view?usp=sharing',
    driveLink: 'https://drive.google.com/file/d/8H9i0J1k2L3m4N5o6P7q-Draft/view?usp=sharing',
    fileMetadata: {
      driveFileId: '8H9i0J1k2L3m4N5o6P7q-Draft',
      fileName: 'Draft_Web_Dev.pdf',
      fileSizeFormatted: '1.2 MB',
      mimeType: 'application/pdf',
    },
    tags: ['Draft', 'HTML'],
    likesCount: 0,
    bookmarksCount: 0,
    downloadsCount: 0,
    commentsCount: 0,
    status: 'rejected',
    rejectionReason: 'Submission is incomplete and contains generic textbook scans with low resolution. Please provide original authored notes or solved university papers.',
    moderationFeedback: 'Submission is incomplete and contains generic textbook scans with low resolution. Please provide original authored notes or solved university papers.',
    createdAt: '2026-08-26T15:00:00.000Z',
    updatedAt: '2026-08-27T10:00:00.000Z',
  },
];

export const mockCommentsList: Comment[] = [
  {
    id: 'comm-1',
    resourceId: 'res-101',
    userId: 'usr-student-01',
    user: mockStudentUser,
    content: 'The BCNF lossy vs lossless decomposition examples on page 14 cleared all my doubts for the CS-301 midterm!',
    status: 'visible',
    createdAt: '2026-08-26T14:20:00.000Z',
    updatedAt: '2026-08-26T14:20:00.000Z',
  },
  {
    id: 'comm-2',
    resourceId: 'res-101',
    userId: 'usr-faculty-01',
    user: mockFacultyUser,
    content: 'Well structured and mathematically accurate proofs. Highly recommended for Semester 5 student revision.',
    status: 'visible',
    createdAt: '2026-08-27T09:15:00.000Z',
    updatedAt: '2026-08-27T09:15:00.000Z',
  },
  {
    id: 'comm-3',
    resourceId: 'res-102',
    userId: 'usr-student-01',
    user: mockStudentUser,
    content: 'The solution for question 4 (Banker\'s Algorithm safe state) matches the university marking scheme perfectly.',
    status: 'visible',
    createdAt: '2026-08-22T16:45:00.000Z',
    updatedAt: '2026-08-22T16:45:00.000Z',
  },
];

export const mockLeaderboardEntries: Record<string, LeaderboardEntry[]> = {
  daily: [
    {
      rank: 1,
      userId: 'usr-student-01',
      user: {
        id: 'usr-student-01',
        name: 'Aarav Sharma',
        avatarUrl: 'AS',
        branch: 'Computer Science (CS-B)',
        semester: 'Sem 5',
      },
      points: 180,
      badge: 'gold',
      resourcesCount: 14,
      downloadsGenerated: 840,
      verified: true,
    },
    {
      rank: 2,
      userId: 'usr-student-02',
      user: {
        id: 'usr-student-02',
        name: 'Sneha Patel',
        avatarUrl: 'SP',
        branch: 'Computer Science (CS-B)',
        semester: 'Sem 5',
      },
      points: 140,
      badge: 'silver',
      resourcesCount: 8,
      downloadsGenerated: 420,
      verified: true,
    },
    {
      rank: 3,
      userId: 'usr-faculty-01',
      user: {
        id: 'usr-faculty-01',
        name: 'Prof. K. Sharma',
        avatarUrl: 'KS',
        branch: 'Computer Engineering',
        semester: 'Faculty',
      },
      points: 110,
      badge: 'platinum',
      resourcesCount: 22,
      downloadsGenerated: 1650,
      verified: true,
    },
  ],
  weekly: [
    {
      rank: 1,
      userId: 'usr-faculty-01',
      user: {
        id: 'usr-faculty-01',
        name: 'Prof. K. Sharma',
        avatarUrl: 'KS',
        branch: 'Computer Engineering',
        semester: 'Faculty Lead',
      },
      points: 890,
      badge: 'diamond',
      resourcesCount: 22,
      downloadsGenerated: 1650,
      verified: true,
    },
    {
      rank: 2,
      userId: 'usr-student-01',
      user: {
        id: 'usr-student-01',
        name: 'Aarav Sharma',
        avatarUrl: 'AS',
        branch: 'Computer Science (CS-B)',
        semester: 'Sem 5',
      },
      points: 760,
      badge: 'gold',
      resourcesCount: 14,
      downloadsGenerated: 840,
      verified: true,
    },
    {
      rank: 3,
      userId: 'usr-alumni-01',
      user: {
        id: 'usr-alumni-01',
        name: 'Rohit Verma',
        avatarUrl: 'RV',
        branch: 'Alumni (Google SDE)',
        semester: 'Batch 2024',
      },
      points: 620,
      badge: 'platinum',
      resourcesCount: 11,
      downloadsGenerated: 1120,
      verified: true,
    },
    {
      rank: 4,
      userId: 'usr-student-02',
      user: {
        id: 'usr-student-02',
        name: 'Sneha Patel',
        avatarUrl: 'SP',
        branch: 'Computer Science (CS-B)',
        semester: 'Sem 5',
      },
      points: 480,
      badge: 'silver',
      resourcesCount: 8,
      downloadsGenerated: 420,
      verified: true,
    },
    {
      rank: 5,
      userId: 'usr-student-03',
      user: {
        id: 'usr-student-03',
        name: 'Rohan Gupta',
        avatarUrl: 'RG',
        branch: 'Computer Science (CS-A)',
        semester: 'Sem 5',
      },
      points: 390,
      badge: 'bronze',
      resourcesCount: 5,
      downloadsGenerated: 210,
      verified: true,
    },
  ],
  monthly: [
    {
      rank: 1,
      userId: 'usr-faculty-01',
      user: {
        id: 'usr-faculty-01',
        name: 'Prof. K. Sharma',
        avatarUrl: 'KS',
        branch: 'Computer Engineering',
        semester: 'Faculty',
      },
      points: 3420,
      badge: 'diamond',
      resourcesCount: 22,
      downloadsGenerated: 1650,
      verified: true,
    },
    {
      rank: 2,
      userId: 'usr-student-01',
      user: {
        id: 'usr-student-01',
        name: 'Aarav Sharma',
        avatarUrl: 'AS',
        branch: 'Computer Science (CS-B)',
        semester: 'Sem 5',
      },
      points: 2840,
      badge: 'gold',
      resourcesCount: 14,
      downloadsGenerated: 840,
      verified: true,
    },
    {
      rank: 3,
      userId: 'usr-alumni-01',
      user: {
        id: 'usr-alumni-01',
        name: 'Rohit Verma',
        avatarUrl: 'RV',
        branch: 'Alumni (Google SDE)',
        semester: 'Batch 2024',
      },
      points: 2150,
      badge: 'platinum',
      resourcesCount: 11,
      downloadsGenerated: 1120,
      verified: true,
    },
  ],
  allTime: [
    {
      rank: 1,
      userId: 'usr-faculty-01',
      user: {
        id: 'usr-faculty-01',
        name: 'Prof. K. Sharma',
        avatarUrl: 'KS',
        branch: 'Computer Engineering',
        semester: 'Faculty Lead',
      },
      points: 12450,
      badge: 'diamond',
      resourcesCount: 22,
      downloadsGenerated: 1650,
      verified: true,
    },
    {
      rank: 2,
      userId: 'usr-alumni-01',
      user: {
        id: 'usr-alumni-01',
        name: 'Rohit Verma',
        avatarUrl: 'RV',
        branch: 'Alumni (Google SDE)',
        semester: 'Batch 2024',
      },
      points: 9820,
      badge: 'diamond',
      resourcesCount: 11,
      downloadsGenerated: 1120,
      verified: true,
    },
    {
      rank: 3,
      userId: 'usr-student-01',
      user: {
        id: 'usr-student-01',
        name: 'Aarav Sharma',
        avatarUrl: 'AS',
        branch: 'Computer Science (CS-B)',
        semester: 'Sem 5',
      },
      points: 6540,
      badge: 'gold',
      resourcesCount: 14,
      downloadsGenerated: 840,
      verified: true,
    },
    {
      rank: 4,
      userId: 'usr-student-02',
      user: {
        id: 'usr-student-02',
        name: 'Sneha Patel',
        avatarUrl: 'SP',
        branch: 'Computer Science (CS-B)',
        semester: 'Sem 5',
      },
      points: 3820,
      badge: 'silver',
      resourcesCount: 8,
      downloadsGenerated: 420,
      verified: true,
    },
  ],
};

export const mockContributorPoints: ContributorPoints[] = [
  {
    id: 'cp-1',
    userId: 'usr-student-01',
    resourceId: 'res-101',
    action: 'upload',
    points: 50,
    createdAt: '2026-08-25T10:00:00.000Z',
  },
  {
    id: 'cp-2',
    userId: 'usr-student-01',
    resourceId: 'res-101',
    action: 'like_received',
    points: 10,
    createdAt: '2026-08-26T12:00:00.000Z',
  },
];

export const mockPopularSubjects = [
  { code: 'CS-301', name: 'Database Management Systems', count: 18 },
  { code: 'CS-302', name: 'Algorithms & Problem Solving', count: 24 },
  { code: 'CS-303', name: 'Operating Systems & Concurrency', count: 16 },
  { code: 'CS-304', name: 'Computer Networks & Protocols', count: 12 },
  { code: 'CS-305', name: 'Software Engineering & Architecture', count: 9 },
  { code: 'CS-306', name: 'Web Technologies & Cloud Stacks', count: 15 },
];

export const mockTrendingTags = [
  '#Normalization',
  '#DeadlockAvoidance',
  '#Dijkstra',
  '#Subnetting',
  '#TCP_Handshake',
  '#BCNF',
  '#SemaphoreSync',
  '#UML',
];

